### PR TITLE
🔨Change Albums to Album

### PR DESCRIPTION
**Pull request by UnknownRori**
### Describe the solution.

Change import variable name from `Albums` to `Album` so it consistent with the file name.

### Describe alternatives you've considered.

We can pretend didn't see the inconsistency.

### Reference

None

### CODE REVIEW

**Comment by BayuDC** [comment]
should we also change the endpoint to `/album` ? and `/picture` for picture page?

**Comment by UnknownRori** [comment]
@BayuDC `/albums` to `/album` seem ok to me but i still prefer `/albums` rather than `/album` because if we go to `album` it mean that there are only 1 album, I suggest we just change the variable name and let the url same as before.

**Comment by BayuDC** [comment]
oke lets use plural for the main page. then how about page for single album? `/albums/<id>` or `/album/<id>`

**Comment by UnknownRori** [comment]
Let's use `/albums/<id>` since the standard writing an endpoint is using nouns, and stackoverflow too do the same thing for example.

`https://stackoverflow.com/questions/` for list all the question.
`https://stackoverflow.com/questions/xxxxxxxx/title-slug` for single question.

Refrence : 
- [Best practices for REST API design from Stackoverflow Blog.](https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design/#h-use-nouns-instead-of-verbs-in-endpoint-paths)
- [REST API Best Practices – REST Endpoint Design Examples from FreecodeCamp.](https://www.freecodecamp.org/news/rest-api-best-practices-rest-endpoint-design-examples/)

**Review by BayuDC — APPROVED** [review]

**Pull request merged**
